name: Start Server and Docker Services

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region where the instance is running'
        required: true
        default: 'us-east-1'
      ec2_instance_name_tag:
        description: 'Value for the Name tag of the running EC2 instance'
        required: true
        default: 'self-analyzation-instance'
      repository_directory_name:
        description: 'The directory name of the cloned repository on the server'
        required: true
        default: 'core-value'

jobs:
  start_services:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Find Stopped EC2 Instance
        id: find_instance
        run: |
          # ... (このステップは変更なし)
          INSTANCE_NAME_TAG="${{ github.event.inputs.ec2_instance_name_tag }}"
          AWS_REGION="${{ github.event.inputs.aws_region }}"
          echo "Searching for a STOPPED instance with tag Name=$INSTANCE_NAME_TAG..."
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=$INSTANCE_NAME_TAG" "Name=instance-state-name,Values=stopped" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text --region "$AWS_REGION")
          if [ -z "$INSTANCE_ID" ]; then
            echo "No stopped instance found with the specified tag."
            echo "INSTANCE_ID=" >> $GITHUB_OUTPUT
          else
            echo "Found stopped instance with ID: $INSTANCE_ID"
            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_OUTPUT
          fi

      - name: Start the EC2 Instance
        if: steps.find_instance.outputs.INSTANCE_ID != ''
        run: |
          # ... (このステップは変更なし)
          INSTANCE_ID="${{ steps.find_instance.outputs.INSTANCE_ID }}"
          AWS_REGION="${{ github.event.inputs.aws_region }}"
          echo "Sending start command to instance $INSTANCE_ID..."
          aws ec2 start-instances --instance-ids "$INSTANCE_ID" --region "$AWS_REGION"
          echo "Waiting for instance $INSTANCE_ID to enter 'running' state..."
          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID" --region "$AWS_REGION"
          echo "Instance $INSTANCE_ID is now successfully running."

      # ★★★★★ 修正点1: IPアドレスを取得する新しいステップを追加 ★★★★★
      - name: Get Instance Public IP
        id: get_ip
        if: steps.find_instance.outputs.INSTANCE_ID != ''
        run: |
          INSTANCE_ID="${{ steps.find_instance.outputs.INSTANCE_ID }}"
          AWS_REGION="${{ github.event.inputs.aws_region }}"
          echo "Fetching Public IP for instance $INSTANCE_ID..."
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids "$INSTANCE_ID" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text --region "$AWS_REGION")
          
          if [ -z "$PUBLIC_IP" ] || [ "$PUBLIC_IP" == "None" ]; then
             echo "Error: Could not retrieve Public IP address for instance $INSTANCE_ID."
             exit 1
          fi

          echo "Found Public IP: $PUBLIC_IP"
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Setup SSH Key
        if: steps.find_instance.outputs.INSTANCE_ID != ''
        run: |
          # ... (このステップは変更なし)
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # ★★★★★ 修正点2: 新しいステップの出力を参照するよう変更 ★★★★★
      - name: Start Docker Compose Services via SSH
        # 参照先を 'steps.get_ip.outputs.PUBLIC_IP' に変更
        if: steps.get_ip.outputs.PUBLIC_IP != ''
        run: |
          echo "Connecting to ${{ steps.get_ip.outputs.PUBLIC_IP }} to start Docker services..."
          REPO_DIR_NAME="${{ github.event.inputs.repository_directory_name }}"

          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@${{ steps.get_ip.outputs.PUBLIC_IP }} << EOF
            echo ">>> [1/2] Navigating to repository directory..."
            cd "/home/ubuntu/${REPO_DIR_NAME}"
            if [ -f "docker-compose.yml" ] || [ -f "docker-compose.yaml" ]; then
              echo ">>> [2/2] Found docker-compose file. Starting existing containers with 'sudo docker compose start'..."
              sudo docker compose start
              echo "Docker containers have been started."
            else
              echo "WARNING: Could not find a docker-compose file in $(pwd). Skipping docker start."
            fi
          EOF